import "@fontsource/jetbrains-mono/100.css"
import "@fontsource/jetbrains-mono/200.css"
import "@fontsource/jetbrains-mono/300.css"
import "@fontsource/jetbrains-mono/400.css"
import "@fontsource/jetbrains-mono/500.css"
import "@fontsource/jetbrains-mono/600.css"
import "@fontsource/jetbrains-mono/700.css"
import "@fontsource/jetbrains-mono/800.css"

import "@fontsource/noto-sans/100.css"
import "@fontsource/noto-sans/200.css"
import "@fontsource/noto-sans/300.css"
import "@fontsource/noto-sans/400.css"
import "@fontsource/noto-sans/500.css"
import "@fontsource/noto-sans/600.css"
import "@fontsource/noto-sans/700.css"
import "@fontsource/noto-sans/800.css"
import "@fontsource/noto-sans/900.css"